GET http://localhost:3000/api/post/getCommentPost
Content-Type: application/json
Authorization: Beared eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZkZGJhMGYzNWFmNTQ1MDExYzE0NjUiLCJpYXQiOjE2Nzk4NjE5NzF9.WGnBm0wzAKLpIa2QT2j6tCfreb7N2sHVcK99rDl1UAU
